name: FaisterSMP
load: STARTUP
main: de.jakkoble.Main
version: 1.0
api-version: 1.16
author: Jakkoble
description: Custom Plugin for Faister Community SMP
libraries:
  - "net.axay:kspigot:1.19.0"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.7.10"
commands:
  block:
    description: Get an Overview of your Blocks
    permission: faister.block
    aliases:
      - blocks
      - b
      - items
      - item
  start:
    description: Start the FaisterSMP
    permission: faister.start
  settings:
    description: Manage the SMP Settings
    permission: faister.settings