name: BlockChange
load: STARTUP
main: de.jakkoble.Main
version: 1.0
api-version: 1.16
author: Jakkoble
description: Custom Plugin for Faister Community SMP
libraries:
  - "net.axay:kspigot:1.19.0"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.7.10"
commands:
  block:
    description: Get an Overview of your Blocks
    aliases:
      - blocks
      - b
  start:
    description: Start the FaisterSMP
    permission: faister.start
  invsee:
    description: Have a look at others inventory
    permission: faister.invsee
  setspawn:
    description: Set the exact Spawnpoint
    permission: faister.setspawn